### ISSUE TITLE
no [intro] key on gui target field (at least on chrome+macosx) forced to use the mouse

### ISSUE THREAD

**Issue by m4ndingo** [epsylon/orb#2]
and that makes me crazy ;)

**Comment by epsylon** [comment]
I see that makes you crazy!.. haha... :-)
I will add some shortkeys to next revision. [intro] included.
Thanks again.

**Comment by m4ndingo** [comment]
por cierto, yo empece a programar esto... esta muy incompleto eh? abri el
repo para q me digas q te parece la idea

https://bitbucket.org/mndg/webserver

inicialmente sirve scripts en python de forma dinámica, es decir, lanzas el
servidor y colocas scripts en la carpeta "files". Luego accedes a ellos vía
url, ej: http://localhost:8081/vars
Puedes modificar los scripts en tiempo real sin necesidad de parar el
servidor, eso le da flexibilidad para hacer cambios rápidos y visualizar el
resultado
luego quiero añadirle otras cosillas interesantes que bueno, ya se irán
viendo si le dedico algo de tiempo, jeje
talue!
