### ISSUE TITLE
Cant Find __Main__

### ISSUE THREAD

**Issue by carterlasalle** [epsylon/orb#6]
```C:\Users\Rocket\orb>  python3 orb --gui
C:\Users\Rocket\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe: can't find '__main__' module in 'C:\\Users\\Rocket\\orb\\orb'```

**Comment by epsylon** [comment]
@RocketNinja15 something wrong on path environment from your python.exe (win32 conf) to the executable path. Is that virtual enviroment correctly created at your system?. 

TIP: https://www.c-sharpcorner.com/article/steps-to-set-up-a-virtual-environment-for-python-development/
